config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ecmwf/cfgrib:
      branch: master
      repo: https://github.com/ecmwf/cfgrib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ecmwf/cfgrib git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-firebrick-uguisu.sh
        container: qc.acc_tacky-russet-chipmunk
  QC.Doc:
    repos:
      github.com/ecmwf/cfgrib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-teal-bracke.sh
        container: qc.doc_stealthy-white-ragdoll
      github.com/ecmwf/cfgrib git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cardinal-bird.sh
        container: qc.doc_hilly-burgundy-shrimp
      github.com/ecmwf/cfgrib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-lemon-sparrow.sh
        container: qc.doc_sleazy-black-cuscus
  QC.Lic:
    repos:
      github.com/ecmwf/cfgrib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-gamboge-robin.sh
        container: qc.lic_surly-emerald-bongo
  QC.Sec:
    repos:
      github.com/ecmwf/cfgrib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-rust-gerbil.sh
        container: qc.sec_gimpy-olivine-burmese
  QC.Sty:
    repos:
      github.com/ecmwf/cfgrib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-razzmatazz-setter.sh
        container: qc.sty_messy-gold-dollar
  QC.Ver:
    repos:
      github.com/ecmwf/cfgrib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-ochre-grasshopper.sh
        container: qc.ver_dorky-olivine-bird
timeout: 5400
