config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ecmwf/cfgrib:
      branch: master
      repo: https://github.com/ecmwf/cfgrib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ecmwf/cfgrib git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-sapphire-quail.sh
        container: qc.acc_hilly-taupe-civet
  QC.Doc:
    repos:
      github.com/ecmwf/cfgrib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-brass-devil.sh
        container: qc.doc_craggy-celadon-turkey
      github.com/ecmwf/cfgrib git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-emerald-schnauzer.sh
        container: qc.doc_chummy-cardinal-rhinoceros
      github.com/ecmwf/cfgrib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cobalt-hyena.sh
        container: qc.doc_snazzy-peach-ibis
  QC.Lic:
    repos:
      github.com/ecmwf/cfgrib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-ruby-rhinoceros.sh
        container: qc.lic_boozy-vermilion-sheepdog
  QC.Sec:
    repos:
      github.com/ecmwf/cfgrib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cyan-tetra.sh
        container: qc.sec_grumpy-linen-butterfly
  QC.Sty:
    repos:
      github.com/ecmwf/cfgrib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-orchid-millipede.sh
        container: qc.sty_lanky-zucchini-weasel
  QC.Ver:
    repos:
      github.com/ecmwf/cfgrib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cerulean-buffalo.sh
        container: qc.ver_cheeky-violet-gopher
timeout: 5400
